### PR TITLE
2019 site

### PR DESCRIPTION
**Pull request by jonathanvila**

### CODE REVIEW

**Comment by abelsromero** [comment]
I cannot build it, I get this error in WSL
```
[asalgadr@BCN-FK6RGH2 jbcnconf_web]$ jekyll build
Configuration file: /mnt/c/Users/asalgadr/jbcnconf/jbcnconf_web/_config.yml
            Source: /mnt/c/Users/asalgadr/jbcnconf/jbcnconf_web
       Destination: /mnt/c/Users/asalgadr/jbcnconf/jbcnconf_web/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
  Liquid Exception: Could not locate the included file 'base.html' in any of ["/mnt/c/Users/asalgadr/jbcnconf/jbcnconf_web/2018/_includes"]. Ensure it exists in one of those directories and, if it is a symlink, does not point outside your site source. in 2019/about.html
jekyll 3.7.4 | Error:  Could not locate the included file 'base.html' in any of ["/mnt/c/Users/asalgadr/jbcnconf/jbcnconf_web/2018/_includes"]. Ensure it exists in one of those directories and, if it is a symlink, does not point outside your site source.
```

**Comment by jonathanvila** [comment]
To build you need to be inside the 2019 folder

**Comment by abelsromero** [comment]
> To build you need to be inside the 2019 folder

This was not necessary for the previous version, I suspect this will make the github pages fail unless some configuration is changed.

About the PR itself:
Tell me the date is wrong 😨 Other that I don't see any issues with this.

**Comment by abelsromero** [comment]
@jonathanvila is this ready?

**Pull request merged**
