### PR TITLE
Add initial schedule 2022 pending 2 talks and keynotes

### PR DESCRIPTION
**Pull request by immavalls**
Adding the schedule while we have a couple of talks and keynotes pending.

### CODE REVIEW

**Review by anyulled — APPROVED** [review]

**Comment by abelsromero** [comment]
I don't see the menu in the preview. Has it been enabled?

**Comment by immavalls** [comment]
This is what I missed I'm afraid...

**Comment by abelsromero** [comment]
No wirries, is just a matter of un-commenting https://github.com/barcelonajug/jbcnconf_web/blob/1114f3157a152bddee58fd1b537215db5d5e6345/2022/_data/menu.yml#L14

**Comment by immavalls** [comment]
@abelsromero @anyulled  I added the schedule menu, can you review it? Thanks!

**Review by anyulled — APPROVED** [review]

**Comment by anyulled** [comment]
Merge whenever you're ready @immavalls

**Comment by immavalls** [comment]
I can't i do not have write access

**Pull request merged**
