### PR TITLE
Prepare 2022

### PR DESCRIPTION
**Pull request by abelsromero**

### CODE REVIEW

**Comment by jonathanvila** [comment]
Should we change from VIRTUAL to PHYSICAL ?
image

**Comment by jonathanvila** [comment]
We should remove menus :
* speakers
* job offers 
* talks
* schedule

**Comment by jonathanvila** [comment]
We should empty data for talks and speakers

**Comment by jonathanvila** [comment]
We should remove all sponsors and supporters except : Red Hat, Ocado, Adevinta, Capitole, Wallapop, Adaptive

**Comment by abelsromero** [comment]
> We should empty data for talks and speakers

I would keep that, it's not displayed unless you access to the urls and is nice to have in case we need to do some changes in the pages.

**Comment by abelsromero** [comment]
> Should we change from VIRTUAL to PHYSICAL ?

How about "IN PERSON", sound more "human" :smile:

**Pull request merged**
