### PR TITLE
feat: resize speaker images

### PR DESCRIPTION
**Pull request by anyulled**
I ran a batch resize for all images in the speaker folder. I need to check with the deployed version if a revert is required on any pictures.

### CODE REVIEW

**Comment by icougil** [comment]
What a great idea my friend!! 👍 😃
Even do.. (and I don't know why)... why there are some files that have increased their size... 🤔

image

why? I don't know...
and it seems it happened to 51 images? 🤔

**Comment by anyulled** [comment]
> What a great idea my friend!! 👍 😃
> Even do.. (and I don't know why)... why there are some files that have increased their size... 🤔
> 
> image
> 
> why? I don't know...
> and it seems it happened to 51 images? 🤔

I will with the laptop, but it's probably because the image was smaller and I set the minimum width of 512px.

I added a second batch for a total of 215 images

**Comment by abelsromero** [comment]
We can add this for regular cleanups, even modify to check inconsistencies in an action

```bash
#!/bin/bash

set -euo pipefail

readonly YEAR=${1:-"2022"}
readonly STAGING_AREA="_staging"
readonly SPEAKER_IMAGES=($(jq -r '.items[].image' "$YEAR/_data/speakers.json"))

stage_valid_images() {
  mkdir -p "$STAGING_AREA"
  echo "Published speakers: ${#SPEAKER_IMAGES[@]}"
  for f in "${SPEAKER_IMAGES[@]}"; do
    mv "$YEAR/$f" "$STAGING_AREA" || true
  done
}

clear_stage_area() {
  rm -rf "$STAGING_AREA"    
}

clean_images() {
  local speaker_images_path="$YEAR/assets/img/speakers"
  # Use array bc du response does not comply with expansion spaces ¯\_(ツ)_/¯
  local images_found=($(du --inodes -s "$speaker_images_path"))
  echo "Deleting images: $((${images_found[0]} - 1))"
  rm -f $speaker_images_path/*.*
  mv $STAGING_AREA/*.* "$YEAR/assets/img/speakers/"
}

main() {
  stage_valid_images
  clean_images
  clear_stage_area
}

main
```

**Comment by anyulled** [comment]
> I am not sure this is a good approach. Most images are not used, maybe the first step would be to remove those? Then we'll only need to review 62 vs 241 of this PR.
> 
> The differences in size may be different factors, the file extension doesn't mean much since internally even the same format has different sub-specs, quality levels, etc. and some add a lot of useless metadata. As a rule of thumb when I resize I remove any extra data (all checkboxs below) and play with the quality, some images work fine at 80, others 90 depending on color gradients for instance. image
> 
> Edit: can you share the script? maybe with that we can help

I cannot find the script I executed, but it was very simple, using [imagemagick](https://imagemagick.org/script/command-line-options.php#resize) something like this

`for I in *; do eval "/opt/magick convert $i -resize 512 -quality 80 $1"; done`

**Comment by anyulled** [comment]
> We can add this for regular cleanups, even modify to check inconsistencies in an action
> 
> ```shell
> #!/bin/bash
> 
> set -euo pipefail
> 
> readonly YEAR=${1:-"2022"}
> readonly STAGING_AREA="_staging"
> readonly SPEAKER_IMAGES=($(jq -r '.items[].image' "$YEAR/_data/speakers.json"))
> 
> stage_valid_images() {
>   mkdir -p "$STAGING_AREA"
>   echo "Published speakers: ${#SPEAKER_IMAGES[@]}"
>   for f in "${SPEAKER_IMAGES[@]}"; do
>     mv "$YEAR/$f" "$STAGING_AREA" || true
>   done
> }
> 
> clear_stage_area() {
>   rm -rf "$STAGING_AREA"    
> }
> 
> clean_images() {
>   local speaker_images_path="$YEAR/assets/img/speakers"
>   # Use array bc du response does not comply with expansion spaces ¯\_(ツ)_/¯
>   local images_found=($(du --inodes -s "$speaker_images_path"))
>   echo "Deleting images: $((${images_found[0]} - 1))"
>   rm -f $speaker_images_path/*.*
>   mv $STAGING_AREA/*.* "$YEAR/assets/img/speakers/"
> }
> 
> main() {
>   stage_valid_images
>   clean_images
>   clear_stage_area
> }
> 
> main
> ```

I'll investigate how to run bash scripts as part of GitHub actions and integrate this script.

**Comment by abelsromero** [comment]
> I'll investigate how to run bash scripts as part of GitHub actions and integrate this script.

No need to rush, in fact to keep things simple we could do a manual cleanup, resize remaining big images we see and get on with other stuff. Automation stuff can spiral into hours and hours of work.

**Review by abelsromero — APPROVED** [review]
awesome!

**Pull request merged**
