### PR TITLE
Add commercetools jobs

### PR DESCRIPTION
**Pull request by alexcuesta**
Added:
- commercetools jobs

### CODE REVIEW

**Comment by alexcuesta** [comment]
Question @icougil @abelsromero @anyulled : I[n commercetools comments](https://docs.google.com/spreadsheets/d/1zV6cq7lANUqvfAQAPj6ESFBCAe6e3RNYaZXlU8F5ge4/edit#gid=1852637077) there is a comment which says:

If possible I would like to add: 

> commercetools - we are:
> The competitive sort: We didn’t become the fastest growing, highest ever valued SaaS software company in digital commerce with nearly 100% year-over-year growth by sitting on the sidelines.
> Inspired: Continually exploring what’s possible — the innovators of headless commerce, the visionaries behind MACH — our patented tech has radically disrupted the world of enterprise ecommerce software - and we are just getting started.
> Valued: Smart, strong, passionate individuals hailing from over 50 countries across the globe, speaking over 43 languages, and collectively embracing diversity, encouraging inclusion, and fostering a culture of caring.
> Driven: We push the limits, technology, and ourselves to retain the trust of some of the world’s leading and fastest growing brands every single day.

I don't know if we want to add this and where.

**Comment by abelsromero** [comment]
I don't see how to fit that in the current format. Maybe they could summarize it we could have an "About us" below "Soft Skills:" block. For that we'd need to ping them for the final test.

**Comment by alexcuesta** [comment]
I'd merge and then update their content once they improve their description text. They can delay it for days or weeks

**Comment by abelsromero** [comment]
> I'd merge and then update their content once they improve their description text. They can delay it for days or weeks

can you chase this in slack? 🙏

**Pull request merged**
