### PR TITLE
Added Helen Scott, Sven Peters and Jason Clark

### PR DESCRIPTION
**Pull request by icougil**

### CODE REVIEW

**Review by anyulled — APPROVED** [review]

**Comment by abelsromero** [comment]
Maybe we should reformat Jason's picture, it's quite high compared with the rest.

**Comment by icougil** [comment]
> Maybe we should reformat Jason's picture, it's quite high compared with the rest.

I don't get it:
image

where is the issue?

**Comment by icougil** [comment]
aaah got it! Yes we have some images that we should improve, like this one...

image

**Comment by icougil** [comment]
better now @abelsromero  ?

**Comment by abelsromero** [comment]
We are already discussing long term solution on another topic, feel free to merge and we can just reformat later.

**Pull request merged**
