### PR TITLE
Improve speakers section

### PR DESCRIPTION
**Pull request by ErnestOrt**
image

### CODE REVIEW

**Comment by abelsalgadoromeroWD** [comment]
I may look as an ass***** but the page desing does not use rounded border. Can we get the same effect without it? :%

**Comment by abelsromero** [comment]
I am just being honest, the effect is great and we need this, but the round effect does not match the rest of the site imo.

**Comment by anyulled** [comment]
Maybe you could apply the rounded border just to the bottom ones in the blue rectangle

**Comment by ErnestOrt** [comment]
Sorry, seems I missed it. Can anyone take a

**Comment by ErnestOrt** [comment]
Sorry, I have clicked the wrong button u_u

**Pull request closed without merging**
