### PR TITLE
Added ACTA Hotels promotional codes

### PR DESCRIPTION
**Pull request by xeeevi**
I created two generic offers in index.html showing 4-star and 3-star hotels, then I created a single card per hotel in accommodation.html page.

### CODE REVIEW

**Comment by cougil** [comment]
Using the approach with bootstrap is much better than a fixed size (as we are using for example with the speakers row). So, instead of having an specific `max-with` for the _hotel_ selector, may be it is much better to use some sylte like this: 
```col-md-4 col-sm-6 col-xs-12 ``` 
Then all the hotel elements will fit completely to the size of the screen of the device, etc. Don't you think so?

**Comment by xeeevi** [comment]
Sure! I'll give it a try this afternoon. Thanks!

**Comment by xeeevi** [comment]
Sorry, I should have used a branch. Be aware that also the commits to announce Mark Heckler as a new speaker are in this pull request.

**Comment by mkbrv** [comment]
@cougil @jonathanvila can we merge this so I can adapt them to the new interface?

**Pull request merged**
