### PR TITLE
Added Carlos Saona

### PR DESCRIPTION
**Pull request by icougil**

### CODE REVIEW

**Review by anyulled — APPROVED** [review]

**Comment by anyulled** [comment]
Something has happened that we're not displaying the social icons at the bottom. I'll dig into that this week
<details><summary>Browser metadata</summary>





```
Path:      /2022/talks.html
Browser:   Chrome 102.0.0.0 on Android 10
Viewport:  424 x 570 @2.549999952316284x
Language:  es-ES
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-1195--jbcnconf.netlify.app%2F2022%2Ftalks.html&os=Android&os_version=10&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-1195--jbcnconf.netlify.app/2022/talks.html) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=629cedf321f9990008c3c4f0&commentID=629cef1cbfea006fb88b4bb6&resolution=resolved)

**Comment by icougil** [comment]
no idea ... TBH... this is what I found in the "log" when running the application... not sure if it's related or not...
image

**Comment by icougil** [comment]
btw, I was able to see it properly in local 🤔 
image

**Comment by anyulled** [comment]
> btw, I was able to see it properly in local 🤔 
> image
> 

No, i wasn't talking about his picture, but the social icons at the bottom of the page. As I said before, it's unrelated to this pull request but I just detected it today

**Comment by abelsromero** [comment]
> no idea ... TBH... this is what I found in the "log" when running the application... not sure if it's related or not...
WIP https://github.com/barcelonajug/jbcnconf_web/pull/1192



> Something has happened that we're not displaying the social icons at the bottom. I'll dig into that this week

Seems a preview thing, fontawesome is not loaded because of some difference in the url :man_shrugging: 
image

Firefox at least displays a placeholder, Chromium doesn't show anything.
image

**Pull request merged**
