### PR TITLE
feat: add published speakers

### PR DESCRIPTION
**Pull request by anyulled**
Copied and pasted the JSON data from the CFP API.

- [x] Update speakers data
- [x] Update talks data
- [x] Add new speaker photos

### CODE REVIEW

**Comment by abelsromero** [comment]
Beware, Ivan is pending approval from employer. Can you remove it and roll back changes in backed :pray:

**Comment by abelsromero** [comment]
Indeed, Ivan is not cleared yet :disappointed:

**Comment by anyulled** [comment]
> Indeed, Ivan is not cleared yet 😞

I will disable his talk and speaker data then.

**Review by icougil — APPROVED** [review]
👍

**Review by abelsromero — APPROVED** [review]

**Comment by abelsromero** [comment]
> I will delete his talk and speaker data then.

Thanks 🥳

**Review by sferrazjr — APPROVED** [review]

**Pull request merged**
