### PR TITLE
WIP: feat: Job offers

### PR DESCRIPTION
**Pull request by anyulled**
- re-styling  the job offers page
- adding job vacancies from the required content document.

### CODE REVIEW

**Review by icougil — COMMENTED** [review]
I'd suggest adding more space between the different companies, to make the the separation more clear

**Comment by icougil** [comment]
image

Better to add an extra space so that the links are not stuck to the sponsor's description? 

And the logos, are they better centered or to the left 🤔?

**Comment by anyulled** [comment]
> Lovely ❤️ 😍 design !!! Thank you mate!!!
> 
> I'd suggest adding more space between the different companies, to make the separation more clear.
> 
> Another interesting thing could be to include this **"Job offers"** section in the menu.
> 
> Btw, I think we can remove the positions if we don't have the information nowadays... or it will break the full page design?
> 
> Also, I'm not 100% sure that adding the location is good or not 🤔 Nowadays that many companies are 100% remote... which one of those offers is mandatory to work from Barcelona or not? Even I like how it looks like, probably in this case it will be much better to remove them and not show anything? What do you think?

Thanks!

- I added an extra margin at the bottom.
- I was thinking to keep this PR in draft until we had all the vacancies from the sponsors and them merge it. I will remove the empty ones and check the design.
- Regarding the location, it just occurred to me because I see that there are 100% remote positions, and also the hybrid ones located somewhere. I'll keep it until we have more data.

**Comment by anyulled** [comment]
> image
> 
> Better to add an extra space so that the links are not stuck to the sponsor's description?
> 
> And the logos, are they better centered or to the left 🤔?

Good, I'll add some more space after the social media icons.
And yes, the logos are centered.

**Comment by icougil** [comment]
That looks amazing! 
Cool about removing the empty ones, I'll include the ones that do not have the right to provide any (all the Regulars).
About the remote / location... not sure, normally the description is not 100% clear. For example, company that offers "remote friendly" it does not mean 100% remote... and also, I'm not sure about the rest. It is mandatory to be in Barcelona? I think can confuse people, don't you think so?

**Comment by anyulled** [comment]
> That looks amazing!
> Cool about removing the empty ones. I'll include those who do not have the right to provide any (all the Regulars).
> About the remote / location, not sure. Usually, the description is not 100% clear. For example, the company that offers "remote-friendly" does not mean 100% remote... and also, I'm not sure about the rest. Is it mandatory to be in Barcelona? I think it can confuse people, don't you think so?

I set the location optional, so if you don't add the field, the text won't appear. I added it because Roche requires the location to be added and requires you to present yourself on the physical instances in the future.

**Comment by icougil** [comment]
> > That looks amazing!
> > Cool about removing the empty ones. I'll include those who do not have the right to provide any (all the Regulars).
> > About the remote / location, not sure. Usually, the description is not 100% clear. For example, the company that offers "remote-friendly" does not mean 100% remote... and also, I'm not sure about the rest. Is it mandatory to be in Barcelona? I think it can confuse people, don't you think so?
> 
> I set the location optional, so if you don't add the field, the text won't appear. I added it because Roche requires the location to be added and requires you to present yourself on the physical instances in the future.

same in Dynatrace 😉

**Pull request merged**
